# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='label',
            field=models.CharField(default='', max_length=400),
        ),
    ]
