# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='path',
            field=models.FilePathField(default='', path='/Users/trn/Dropbox/projects/django/cars/media/results'),
            preserve_default=False,
        ),
    ]
