# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_auto_20180122_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('N/A', 'N/A'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('PICKUP', 'PICKUP'), ('MINIVAN', 'MINIVAN'), ('HATCHBACK', 'HATCHBACK'), ('CONVERTIBLE', 'CONVERTIBLE'), ('COUPE', 'COUPE'), ('WAGON', 'WAGON')], default='N/A', max_length=15),
        ),
    ]
