# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_auto_20180122_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='url',
            field=models.URLField(default='https://www.autotrader.com/', max_length=400),
        ),
    ]
