# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_car_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
