import os
import pickle

import numpy as np

from keras import backend as K
from keras.applications import InceptionV3
from keras.layers import Dense
from keras.models import Sequential
from keras.preprocessing.image import load_img, img_to_array

TEST_LABELS = [
    'Aston_Martin-Martin_V8_Vantage_Convertible-2012',
    'Aston_Martin-Martin_Virage_Convertible-2012',
    'Aston_Martin-Martin_V8_Vantage_Coupe-2012',
    'Dodge-Ram_Pickup_3500_Quad_Cab-2009',
    'Ford-E_Series_Wagon_Van-2012',
]



IMG_WIDTH, IMG_HEIGHT = 299, 299
if K.image_data_format() == 'channels_first':
    INPUT_SHAPE = (3, IMG_WIDTH, IMG_HEIGHT)
else:
    INPUT_SHAPE = (IMG_WIDTH, IMG_HEIGHT, 3)
NB_CLASSES = 196

WEIGHTS_PATH = os.path.join(
    os.path.expanduser('~'), 'Dropbox', 'projects',
    'cars', 'data', 'InceptionV3',
    'InceptionV3_13_10_20.h5'
    )
LOOKUP_PATH = os.path.join(
    os.path.expanduser('~'), 'Dropbox', 'projects',
    'cars', 'data', 'notebooks', '6_predictions_with_trained_model',
    'lookup_dicto.pkl'
    )

def load_model():
    """
    Initializes and loads pretrained weights into keras model to be used for predictions
    """
    conv_base = InceptionV3(
        weights='imagenet',
        include_top=False,
        pooling='avg',
        input_shape=INPUT_SHAPE
    )

    pred_layer_config = {
        'activation': 'softmax',
        'activity_regularizer': None,
        'bias_constraint': None,
        'bias_initializer': {'class_name': 'Zeros', 'config': {}},
        'bias_regularizer': None,
        'kernel_constraint': None,
        'kernel_initializer': {'class_name': 'VarianceScaling',
                               'config': {
                                   'distribution': 'uniform',
                                   'mode': 'fan_avg',
                                   'scale': 1.0,
                                   'seed': 8}
                              },
        'kernel_regularizer': None,
        'name': 'predictions',
        'trainable': True,
        'units': NB_CLASSES,
        'use_bias': True}

    model = Sequential()
    model.add(conv_base)
    model.add(Dense(**pred_layer_config))

    model.load_weights(WEIGHTS_PATH)

    return model

def prepare_image(image_path):
    """
    Converts image found in image_path to a numpy array that
    can be used by keras model to make a prediction
    """
    input_image = load_img(image_path, target_size=(IMG_HEIGHT, IMG_WIDTH))
    input_image = img_to_array(input_image)
    input_image = np.expand_dims(input_image, axis=0)
    input_image = input_image / 255.
    return input_image

def load_lookup_dicto():
    """
    returns lookup_dictonary necessary to interpret keras model predictions
    """
    with open(LOOKUP_PATH, 'rb') as f:
        lookup_dicto = pickle.load(f)
    return lookup_dicto

def top5_predictions(model, image_path, lookup_dicto):
    """
    returns populated contect_dict for classifier.views.predictions 
    view based on the predictions made by a pretrained keras model

    Inputs:
    -model generated by load_model
    -image path to image to be used for prediction
    -lookup_dicto generated by load_lookup_dicto

    Output:
    ranked list of labels
    """
    input_image = prepare_image(image_path)
    prediction = model.predict(input_image)
    top_5 = prediction[0].argsort()[-5:][::-1]
    labels = []
    for idx in top_5:
        labels.append(lookup_dicto.get(idx))
    

    context_dict = {
        'image': os.path.basename(image_path),
        
        'prediction1_path': 'predictions/' + labels[0] + '_0.jpg',
        'prediction1_label': 'Top prediction: {}'.format(labels[0]),
        'prediction1_link': 'https://www.cars.com',

        'prediction2_path': 'predictions/' + labels[1] + '_0.jpg',
        'prediction2_label': 'Second prediction {}'.format(labels[1]),
        'prediction2_link': 'https://www.autotrader.com', # This one seems to have an easy search url

        'prediction3_path': 'predictions/' + labels[2] + '_0.jpg',
        'prediction3_label': 'Third prediction {}'.format(labels[2]),
        'prediction3_link': 'https://www.carvana.com',
        }

    return context_dict

def load_test_predictions():
    """
    Provides a static predictions dictionary to test the app
    without having to load the full keras model to memory each time the server starts
    """
    return TEST_LABELS
